### ISSUE TITLE
Direction in 2.0 wave?

### ISSUE THREAD

**Issue by Lexcess** [OdeToCode/BeaverLeague#1]
Hi, I just watched your 'Opinionated Approach' talk from NDC. Some very interesting points there, and a few conclusions I was heartened to see echoed my own (in memory integration testing over unit testing for one). Thanks for putting it together.

Specifically on this repo though, have you had thoughts about updating it for the new 2.0 wave? Obviously it's only recently hit preview, so a more interesting question for me is less when but if you did, would you continue with server side MVC? 

Server side Web API with client side views (React+Redux/Angular) seem to be a popular direction right now. I'm curious if that is a direction you would consider here and if not why not. For example, are there weaknesses going full client side, is it not worth the effort of such a major change of approach but if you did it all over again you might consider it? Is there a tipping point one way or the other for you? I'd be interested to hear your opinionated thoughts :)

**Comment by OdeToCode** [comment]
I will be updating for 2.0 in a few months. I still think the choice of using client frameworks versus HTML rendering really depends on the app, the business, and the users.

**Comment by Lexcess** [comment]
Thanks for the reply. 

I agree that it is usually a 'it depends' kind of decision. I was interested because there seems to be an increasing opinion that client frameworks are the default and it'd be a big issue (typically developer skill set) to go the other way.
